# This is a basic workflow to help you get started with Actions

name: Deploy
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to deploy blog.
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive # Checkout private submodules(themes or something else).
    - name: update submodule branch
      run: |
        git submodule sync
        git submodule update --remote
    - name: Install npm denpendency 
      uses: actions/setup-node@v2
      with:
        node-version: '12.22.7'
        cache: 'npm'
    - run: npm install -g hexo-cli
    - run: npm install
    - name: Install ssh-key
      uses: kielabokkie/ssh-key-and-known-hosts-action@v1
      with:
        ssh-private-key: ${{ secrets.ID_RSA }}
        ssh-host: github.com
    - name: Hexo Deploy
      run: |
        echo "${{ secrets.ID_RSA }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
        git config --global user.email "hff1996723@gmail.com"
        git config --global user.name "github/holmofy"
        hexo clean && hexo g && hexo d

